name: Flask App CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Flask app
      run: |
        nohup python app.py &
        sleep 10
        tail -n 10 nohup.out
      env:
        FLASK_ENV: development
        ADMIN_EMAILS: "admin@example.com,anotheradmin@example.com"

    - name: Check app status
      run: |
        curl -f http://127.0.0.1:5000/
