name: Beehive Flask App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Show current directory
      run: pwd

    - name: Set environment variables
      run: |
        echo "ADMIN_EMAILS=${{ secrets.ADMIN_EMAILS }}" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}" >> $GITHUB_ENV
      env:
        FLASK_ENV: development

    - name: Start Flask app
      run: |
        nohup python app.py &
        sleep 10
        tail -n 10 nohup.out
      env:
        FLASK_ENV: development

    - name: Check app status
      run: |
        curl -f http://127.0.0.1:5000/
