name: Flask App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Use the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust if your requirements file is named differently

    - name: Start Flask app
      run: |
        nohup python app.py &
      env:
        FLASK_ENV: development  # Set environment variables if needed

    - name: Check app status
      run: |
        sleep 5  # Wait for the app to start
        curl -f http://127.0.0.1:5000/  # Check if the app is up
